<a href="https://colab.research.google.com/github/Pravi1718/numpy/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #numpy means numerical python

In [2]:
l=[1,2,3,4]
z=np.array(l)
z

array([1, 2, 3, 4])

In [3]:
l=[1,2.4,3,5]
z=np.array(l)
z

array([1. , 2.4, 3. , 5. ])

In [4]:
l=[1,2,3,'manu']
z=np.array(l)
z

array(['1', '2', '3', 'manu'], dtype='<U21')

In [5]:
l=[1,2,3,4,5]
z=np.array(l)
print(z)
z[4]
z[2:]
z[-2]

[1 2 3 4 5]


np.int64(4)

In [6]:
l=[1,2,3,4,5]
z=np.array(l)
z[-1:-4:-1]

array([5, 4, 3])

In [7]:
l=[1,2,3,4,5]
z=np.array(l)
z[-1::-1]

array([5, 4, 3, 2, 1])

In [8]:
z.ndim


1

In [9]:
np.size(z)

5

In [11]:
z.shape#to know no of rows and columns

(5,)

In [13]:
z=np.array([[1,2],[3,4]])
z

array([[1, 2],
       [3, 4]])

In [14]:
np.shape(z)

(2, 2)

In [15]:
np.size(z)

4

In [16]:
z.ndim

2

In [18]:
z=np.array([[[1,2],[2,3]],[[1,2],[3,4]]])
print(z)
print(np.size(z))
print(np.shape(z))
print(z.ndim)

[[[1 2]
  [2 3]]

 [[1 2]
  [3 4]]]
8
(2, 2, 2)
3


In [19]:
#2*3 matrix
z=np.array([[1,2,3],[4,5,6]])
z

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
#4*2 matrix
z=np.array([[1,2],[3,4],[5,6],[7,8]])
z

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [21]:
#4*4 matrix
z=np.array([[1,2,3,4],[2,3,4,5],[8,9,7,6],[1,6,7,8]])
z

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [8, 9, 7, 6],
       [1, 6, 7, 8]])

In [28]:
#indexing
print(z[2,2])
print(z[3,1])
print(z[1,2:])
print(z[1:3,1:3])
print(z[0:3,1:3]) #0:3 means no of rows and 1:3 means no of columns
print(z[1:,1:])

7
6
[4 5]
[[3 4]
 [9 7]]
[[2 3]
 [3 4]
 [9 7]]
[[3 4 5]
 [9 7 6]
 [6 7 8]]


In [30]:
#zero matrix
z=np.zeros([2,2],dtype=int) #dtype is used to change float to int or anything
z

array([[0, 0],
       [0, 0]])

In [ ]:
z=np.zeros([2,2])
z

In [31]:
z=np.zeros([2,2,2],dtype=complex)
z

array([[[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]]])

In [32]:
#one matrix
z=np.ones([2,2])
print(z)

[[1. 1.]
 [1. 1.]]


In [36]:
#create two 2*2 matrix
a=np.array([[1,2],[2,3]])
b=np.array([[5,6],[8,9]])
print(a+b)
print(a-b)
print(a*b) #not a matrix multiplication
#to multiply 2 matrix use a@b or a.dot(b)
print(a/b)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-6 -6]]
[[ 5 12]
 [16 27]]
[[0.2        0.33333333]
 [0.25       0.33333333]]


In [39]:
#full matrix
z=np.full([2,2,3],8)
print(z)

[[[8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]]]


In [1]:
import numpy as np

In [3]:
#identity matrix
a=np.eye(3,dtype=int)
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [4]:
b=np.identity(4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
#create a 3x3 matrix
a=np.array([[1,2,3],[4,5,6],[4,6,8]])
print(a)
print(a.shape)
z=a.reshape(1,9)
z

[[1 2 3]
 [4 5 6]
 [4 6 8]]
(3, 3)


array([[1, 2, 3, 4, 5, 6, 4, 6, 8]])

In [9]:
b=np.arange(1,10)
print(b)

[1 2 3 4 5 6 7 8 9]


In [10]:
#create a 5x2 matrix without using np.array
b=np.arange(1,11).reshape(5,2)
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])